name: ğŸš€ Deploy website on push
on: 
  push:
    branches:
      - main
      - master
      - 'releases/**'
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3

    - name: ğŸ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: intl-70.1
        tools: composer

    - name: ğŸ Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: ğŸš© Install Node Dependencies
      run: |
        npm install --global yarn
        yarn install

    - name: ğŸš© Install PHP Dependencies
      run: composer install --no-dev

    - name: ğŸ”¨ Minify Build Tailwind CSS
      run: yarn build:minify

    - name: ğŸ“‚ Sync Deploy files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        security: strict
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password:  ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir:  ${{ secrets.FTP_BASE_DIR }}
        exclude: |
          LICENSE
          .htaccess
          .env
          env
          .git*
          .git*/**
          .husky/**
          .github/**
          tests/**
          node_modules/**
          writable/cache/**
          writable/debugbar/**
          writable/logs/**
          writable/session/**
          writable/uploads/**